Traceback (most recent call last):
  File "/home/runner/py3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/py3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/py3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/py3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/runner/py3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/py3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/py3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
import cbsyst as cb
plt.rcParams['font.size'] = 14

sw = cb.Csys(pCO2=np.linspace(250, 450), TA=2300)

preind = 270
modern = 415

plt.plot(sw.pCO2, sw.pHtot, color='k')
plt.xlabel('pCO2 (ppm)')
plt.ylabel('$pH_{Total}$')
plt.xlim(250, 450)

plt.axvline(preind, color='C0', lw=5, alpha=0.5)
plt.text(preind + 5, 8.18, 'Pre-Industrial', color='C0', ha='left', va='bottom', fontsize=14)

plt.axvline(modern, color='C1', lw=5, alpha=0.5)
plt.text(modern - 5, 8.025, 'Modern', color='C1', ha='right', va='top', fontsize=14);

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mcbsyst[39;00m [38;5;28;01mas[39;00m [38;5;21;01mcb[39;00m
[1;32m      4[0m plt[38;5;241m.[39mrcParams[[38;5;124m'[39m[38;5;124mfont.size[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;241m14[39m
[1;32m      6[0m sw [38;5;241m=[39m cb[38;5;241m.[39mCsys(pCO2[38;5;241m=[39mnp[38;5;241m.[39mlinspace([38;5;241m250[39m, [38;5;241m450[39m), TA[38;5;241m=[39m[38;5;241m2300[39m)

File [0;32m~/py3/lib/python3.10/site-packages/cbsyst/__init__.py:1[0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcbsyst[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcbsyst[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcbsyst[39;00m[38;5;21;01m.[39;00m[38;5;21;01mhelpers[39;00m [38;5;28;01mimport[39;00m data_out, Bunch
[1;32m      4[0m VERSION [38;5;241m=[39m [38;5;124m'[39m[38;5;124m0.4.0-alpha[39m[38;5;124m'[39m

File [0;32m~/py3/lib/python3.10/site-packages/cbsyst/cbsyst.py:7[0m, in [0;36m<module>[0;34m[0m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mkgen[39;00m
[0;32m----> 7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcbsyst[39;00m[38;5;21;01m.[39;00m[38;5;21;01mhelpers[39;00m [38;5;28;01mimport[39;00m Bunch, maxL
[1;32m      8[0m [38;5;66;03m# from cbsyst.MyAMI_V2 import MyAMI_K_calc, MyAMI_K_calc_multi, MyAMI_K_calc_direct[39;00m
[1;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcbsyst[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcarbon[39;00m [38;5;28;01mimport[39;00m calc_C_species, calc_revelle_factor, pCO2_to_fCO2, fCO2_to_CO2

File [0;32m~/py3/lib/python3.10/site-packages/cbsyst/helpers.py:1[0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01muncertainties[39;00m[38;5;21;01m.[39;00m[38;5;21;01munumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01munp[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m

[0;31mModuleNotFoundError[0m: No module named 'uncertainties'
ModuleNotFoundError: No module named 'uncertainties'

